# NUMPY

In [3]:
#LIBRARIES
import numpy as np

In [31]:
arr1 =np.random.rand(3,2)
print(arr1)

[[0.46885869 0.27977204]
 [0.68650739 0.6485422 ]
 [0.97659024 0.43354353]]


In [32]:
#2D ARRAY OF SIZE (3,2)
arr2= np.ones((3,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [49]:
print(arr1+3.2)

[[3.66885869 3.47977204]
 [3.88650739 3.8485422 ]
 [4.17659024 3.63354353]]


In [28]:
#MULTIPLYING ARRAYS
print(arr1+arr2)


[[1.07308395 1.48543699]
 [1.74264833 1.87044751]
 [1.2301004  1.84777264]]


In [29]:
np.dot(3,4)

12

In [30]:
np.dot(arr1, arr2)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [41]:
X=arr1[:,0:2]
Y=arr2[:,0:2]

In [63]:
x=np.delete(X,2, axis =0)
y=np.delete(Y,2, axis =0)
Result=np.dot(x,y)
Result

array([[0.74863073, 0.74863073],
       [1.33504959, 1.33504959]])

In [65]:
xSlice=(Result[:1])
xSlice

array([[0.74863073, 0.74863073]])

In [1]:
arr1.reshape(3)

NameError: name 'arr1' is not defined